SELECT nombre FROM producto;
SELECT nombre, precio FROM producto;
SELECT * FROM producto;
SELECT nombre, precio, round(precio * 1.1, 2) FROM producto;
SELECT nombre as 'Nombre del producto', precio as EUR, round(precio * 1.1, 2) as USD FROM producto;
SELECT upper(nombre) as NOMBRE, precio FROM producto;
SELECT lower(nombre) as NOMBRE, precio FROM producto;
SELECT nombre, upper(substring(nombre,1,2)) as 'first two letters' FROM fabricante;
SELECT upper(nombre),  round(precio) FROM producto;
SELECT upper(nombre), floor(precio) FROM producto;
SELECT codigo_fabricante FROM producto;
SELECT DISTINCT codigo_fabricante FROM producto;
SELECT nombre FROM fabricante ORDER BY nombre ASC;
SELECT nombre FROM fabricante ORDER BY nombre DESC;
SELECT nombre, precio FROM producto ORDER BY nombre ASC, precio DESC;
SELECT * FROM fabricante LIMIT 5;
SELECT * FROM fabricante LIMIT 3,2;
SELECT nombre, precio FROM producto ORDER BY precio ASC LIMIT 1;
SELECT nombre, precio FROM producto ORDER BY precio DESC LIMIT 1;
SELECT nombre FROM producto where codigo_fabricante = 2;
SELECT p.nombre, precio, f.nombre FROM producto p JOIN fabricante f ON (p.codigo_fabricante = f.codigo);
SELECT p.nombre, precio, f.nombre FROM producto p JOIN fabricante f ON (p.codigo_fabricante = f.codigo) ORDER BY f.nombre ASC;
SELECT p.codigo, p.nombre, p.codigo_fabricante, f.nombre FROM fabricante f JOIN producto p ON (p.codigo_fabricante = f.codigo);
SELECT  p.nombre, p.precio, f.nombre as 'nombre de fabricante' FROM producto p JOIN fabricante f ON (p.codigo_fabricante = f.codigo) ORDER BY precio ASC LIMIT 1;
SELECT  p.nombre, p.precio, f.nombre as 'nombre de fabricante' FROM producto p JOIN fabricante f ON (p.codigo_fabricante = f.codigo) ORDER BY precio DESC LIMIT 1;
SELECT * FROM producto p JOIN fabricante f ON (p.codigo_fabricante = f.codigo) WHERE f.nombre = 'lenovo';
SELECT * FROM producto p JOIN fabricante f ON (p.codigo_fabricante = f.codigo) WHERE (f.nombre = 'crucial' and p.precio > 200);
SELECT * FROM producto p JOIN fabricante f ON (p.codigo_fabricante = f.codigo) WHERE f.nombre = 'asus' or  f.nombre = 'hewlett-packard' or f.nombre = 'seagate';
SELECT * FROM producto p JOIN fabricante f ON (p.codigo_fabricante = f.codigo) WHERE f.nombre in ('asus', 'hewlett-packard', 'seagate');
SELECT  p.nombre, p.precio FROM producto p JOIN fabricante f ON (p.codigo_fabricante = f.codigo) WHERE f.nombre LIKE '%e';
SELECT  p.nombre, p.precio FROM producto p JOIN fabricante f ON (p.codigo_fabricante = f.codigo) WHERE f.nombre LIKE '%w%';
SELECT  p.nombre, p.precio, f.nombre as 'nombre de fabricante' FROM producto p JOIN fabricante f ON (p.codigo_fabricante = f.codigo) where p.precio >= 180 ORDER BY p.precio DESC, p.nombre ASC;
SELECT DISTINCT f.codigo, f.nombre FROM fabricante f JOIN producto p ON (p.codigo_fabricante = f.codigo);
SELECT f.*, p.nombre as 'nombre del producto' FROM fabricante f LEFT JOIN producto p ON (p.codigo_fabricante = f.codigo);
SELECT f.*, p.nombre as 'nombre del producto' FROM fabricante f LEFT JOIN producto p ON (p.codigo_fabricante = f.codigo) WHERE p.nombre is null;
SELECT p.nombre FROM producto p WHERE p.codigo_fabricante = (SELECT codigo from fabricante where nombre = 'lenovo');
SELECT * FROM producto WHERE precio = (SELECT max(precio) FROM producto WHERE codigo_fabricante = (SELECT codigo from fabricante WHERE nombre = 'lenovo'));
SELECT p.nombre FROM producto p JOIN fabricante f ON (p.codigo_fabricante = f.codigo) WHERE f.nombre = 'lenovo' ORDER BY p.precio DESC LIMIT 1;
SELECT p.nombre FROM producto p JOIN fabricante f ON (p.codigo_fabricante = f.codigo) WHERE f.nombre = 'Hewlett-Packard' ORDER BY p.precio ASC LIMIT 1;
SELECT p.* FROM producto p WHERE p.precio >= (SELECT max(p.precio) FROM producto p JOIN fabricante f ON (p.codigo_fabricante = f.codigo) WHERE f.nombre = 'lenovo');
SELECT  p.* FROM producto p JOIN fabricante f ON (p.codigo_fabricante = f.codigo) WHERE f.nombre = 'asus' and p.precio > (SELECT round(avg(p.precio), 2) FROM producto p JOIN fabricante f ON (p.codigo_fabricante = f.codigo) WHERE f.nombre = 'asus');


